# Generated by Django 4.1.4 on 2023-04-06 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank='False', max_length=450)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arthur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='posts_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
