# Generated by Django 4.1.4 on 2023-04-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
