# Generated by Django 4.1.4 on 2023-04-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='arthur',
            new_name='author',
        ),
    ]
