# Generated by Django 4.1.4 on 2023-04-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_arthur_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=450),
        ),
    ]
