# Generated by Django 4.1.4 on 2023-04-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_rename_post_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
    ]
